[env:ttgo-t-beam]
platform = espressif32
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Configuración del sistema de archivos para cargar tu JSON
board_build.filesystem = spiffs
board_build.partitions = default.csv

lib_deps =
    ; Comunicación y RF
    sandeepmistry/LoRa @ ^0.8.0
    peterus/APRS-Decoder-Lib @ ^0.0.6
    
    ; Sensores y Gestión de Energía
    mikalhart/TinyGPSPlus @ ^1.0.3
    lewisxhe/XPowersLib @ ^0.2.1
    
    ; Pantalla OLED
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9
    
    ; Utilidades y Sistema
    bblanchon/ArduinoJson @ ^6.21.4
    mathertel/OneButton @ ^2.5.0
    paulstoffregen/Time @ ^1.6.1
    peterus/esp-logger @ ^1.0.0
