[env:ttgo-t-beam]
platform = espressif32
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200

lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    mikalhart/TinyGPSPlus @ ^1.0.3
    lewisxhe/AXP202X_Library @ ^1.1.3
    bblanchon/ArduinoJson @ ^6.21.3